{
 "title": "Trouble box [SPOG]",
 "description": "Single pane of glass Trouble box app",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(up, kubernetes_namespace)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Disponibilidade",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (kubernetes_namespace) (\n  avg_over_time(up{app=\"trouble-box\", kubernetes_namespace=~\"$namespace\"}[5m])\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disponibilidade Média (última hora)",
   "type": "timeseries",
   "description": "Disponibilidade Média (última hora)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (kubernetes_namespace) (\n  avg_over_time(up{app=\"trouble-box\", kubernetes_namespace=~\"$namespace\"}[1h])\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disponibilidade < 99.9% (SLO)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(kubernetes_namespace) (\n  avg_over_time(up{app=\"trouble-box\"}[5m])\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS Atual",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kubernetes_namespace) (\n  rate(troublebox_orders_total{kubernetes_namespace=~\"$namespace\"}[1m])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}